version: "3.7"
services:
  db:
    build: development/db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - DB_APP_NAME=happ-db
      - DB_APP_USER=happ-db
      - DB_APP_PASS=happ-db
    volumes:
      - "./data:/var/data/db"